server:
  port: 8181
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/park?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: hxqhxq521  # 使用您的实际密码
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    open: true
    database: 1
    host: 127.0.0.1
    port: 6379
jwt:
  secret: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4K67DMlSPXbgG0MPp0gH
  expire: 86400000
  subject: door
upload:
  numberUrl: D:/park/upload/number/
  excel: D:/park/upload/excel/
  urlPrefix: http://localhost:8181/

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.southwind.entity
  configuration:
    map-underscore-to-camel-case: true

alipay:
  app-id: 2021000147668365
  private-key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDMYMCZTuLDD/WXUSad/wKQvLFqLWIRTNt8VdhyiSUs6h8B6d6kiUrI75Nng3+rlL2/91Ba5aokljLLdNdNvHN5AOLUyziKMGO68h7eDUTzhA4QITGp2LU6drQ5wApfrQ/ZMETJd4QFXokVdsBUdUOOKVQrMKl3xG71vAxxluN14QkFe6s/bnGm6HOvfhPf95ov11hQXh7ZCR5MPXmQGkjLpX2iWXLpMwQfL9xa9Ddc0tIRa1KLcUBcU2zVaCtZccxZusTl/DqaTo1xQC4lx3h61/cP2sm1QXJ+Wk4IOMdJZizA0WEMDXo3udQyPcJ9DPE4sOw0/5jASOhvB+YVCpExAgMBAAECggEAKRVR4f9/ieKNZcuETcJTS7ECoOtaiUu/2zCOgAedl3fAn+vZO431oIq4QNioM1+E/S/D0WHVX+FpeIiWNyQouiw5bLklNnIfuhatqclVEPZ8tTVW/GN5mrT96ZX2/+CUDP6s9Sq3OTUVrWDfrJqd59fa+YugpVixTWhtv++q7ajg5z6pQXWnPU0S6wH+xwg9TUVIsxzmU01u7It07sciOSWwlaO8f9t8GNl+KdWnyRzof0ABZ8QksvYX8POH24yvfW9ItDebk6BVJ/HzrFsfqjbQA94z88uOftWEir658svs6duDnjqjdwN2B5uRHhWDGgaoTNxYT58Xmb4AMbm6eQKBgQDlPBuUJA2yVLOM1AGrzbQxfhFDcCmhIxmDKRZTAkuUC/3MOEh5u4M6wxFucN9Jr4+QTpfaftggy3ZY2n8ssUya0tIc5g7/lIh5ZYlmJPlzv3/q9B0VcFV6jyk58I7A3BW3bDPDhuMG1/205iBLQzuN1Qk3yKEzZR/a2WaByIx3cwKBgQDkPaqLdva2K1//iOGdGfBPcStwyE+rD8Gf/uyDqyYXuxwO72dnt4AP2nmf3kU+ievlsClOx5VsEYc/cvj9vfALq7LJlpkX04YXnarRhNnBUJzpHf2ts4AnJaP5T0sazR4YfNUB34VIZYvo+6J8DURdc7X2MPiqOXn74o0HL1iDywKBgQDM53ara7LGhgncxyEbRgtc9hhOVLMRc0N5xz9KQdH26uUZJ/I4xhEedIFfXAtrXT+RuX7pctqULeqCsARfmbgk6G+iH06mzElVYhp4MHK+MR4RkdVxdXEi1Vb/kHS6FcBfrZtzml3Snz0L92xEejuAoz3THEZjn2/i+tMzDWXp2wKBgCK4xuMkm++mtZn4RupRcd+EBenIb2ZEpV4jt/Nn7AmcK26SORbsMY033VzWwY38CWkN3ZrgffjMydh7MynW5VfBLRfB01Rul22sTLpHDaF9FAHa0CbGse5CqalZyMExBy0OgJEiYfJbkGdHMLbShd35pmrnlEzBJa+ODYpUR5D1AoGBANg4l0lVpC7aTP7MPpM4jW5QhOKdEQzSnrrORMmNZx8iocJeXcjYp4Z0NUubMSC0iUT+o5XczGGxb0bG2YLJJqdrx68qgwlIFILMzE8eJArYOOxrEwTfchkhHzrN6UwHrrndlpQ06zrQnNPJa/wuLyFpqujIdnz+/yG3yW9c4zSl
  public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApmB1xKiZtSSoeWnqWsws7iprpGlTXODrT9/0FM4zCStQQHGeOQdMZlYoYlZU/+TRJE/kSJQY7U0ti08/OFBujeNerzBHxp+kJTywqGgBdAL91hoojOIh5gpqdyv+TL4EFswo+PlFa3iXzvrjMdEDq8weyO54FOvL9M7GoXH+KWVRz2wVo/lJhTSmqht7OL7Q5t85v/SWXG6eUG/f76nuFOMHYGTcaZylWeczTY2APWVCGvS5zuZV+zLoCzDJWLNIBEddswNiJFvoQh6iaq7izHbwGaE9rQFWTT5vOh6+jzkj61ivv+g3W9IjerxApqxGw3bDc4uTdVzc5NwDW+yI/wIDAQAB
  gateway: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  notify-url: http://4in4kn.natappfree.cc/api/pay/alipay/notify
  return-url: http://4in4kn.natappfree.cc/api/pay/alipay/return
  sign-type: RSA2
  charset: utf-8
  format: json

wxpay:
  app-id: 你的微信公众号ID
  mch-id: 你的微信商户号
  mch-key: 你的微信商户密钥
  notify-url: http://你的域名/api/pay/wxpay/notify
  trade-type: JSAPI
